export const PHYSICS_DICE_CONFIG = {
  defaults: {
    diceSize: 0.76,
    mass: 1.15,
    gravity: 18,
    friction: 0.74,
    restitution: 0.34,
    linearDamping: 0.16,
    angularDamping: 0.2,
    throwForce: 3,
    simulationHz: 60,
  },
  quality: {
    eco: { pixelRatio: 1, shadows: false, shadowSize: 0 },
    balanced: { pixelRatio: 1.5, shadows: true, shadowSize: 512 },
    high: { pixelRatio: 2, shadows: true, shadowSize: 1024 },
  },
  scene: {
    baseDiceSize: 0.76,
    colliderHalfRatio: 0.487,
    bowlDiceScale: 0.72,
    resultDiceScale: 1.35,
    resultGap: 0.12,
    selectionBorder: { offsetRatio: 0.045, widthRatio: 0.018, cornerRadiusRatio: 0.151 },
    camera: { simulationHalfWidth: 4.25, resultHalfWidth: 4.25, minHalfHeight: 3.35 },
    tray: {
      halfSize: 2.9,
      rollingHalfWidth: 2.5,
      rollingMinZ: -1.35,
      rollingMaxZ: 2.5,
      entryApronMaxX: 5.5,
      slotZ: -2.28,
      rimWidth: 0.18,
      rimHeight: 0.24,
      separatorZ: -1.5,
    },
    keepSlots: {
      diceScale: 0.72,
      gapRatio: 0.12,
      borderOffsetRatio: 0.065,
      borderWidthRatio: 0.016,
      cornerRadiusRatio: 0.151,
      fillOpacity: 0.64,
      frameOpacity: 0.42,
      shadowOpacity: 0.16,
      shadowOffset: 0.035,
      moveDurationMs: 380,
    },
    bowl: {
      autoTiltMs: 2400,
      startX: 3.35,
      startZ: 0.45,
      hoverY: 0.28,
      tiltDurationMs: 520,
      rotationPivotY: 0.72,
      tiltTravelX: 0.48,
      tiltTravelZ: 0,
      tiltLiftY: 0.05,
      spillPushDurationMs: 220,
      spillPushTravelX: 0,
      exitDurationMs: 520,
      exitTravelX: 3.2,
      exitLiftY: 0.62,
      tiltDegrees: 104,
      visualTiltDegrees: 104,
      tiltDirection: 1,
      shakeIntervalMs: 105,
      shakeOffsetX: 0.13,
      shakeOffsetZ: 0.11,
      shakeYaw: 0.075,
      shakeFollowStrength: 0.055,
      shakeCenterStrength: 0.025,
      shakeOrbitStrength: 0.075,
      shakeLiftImpulse: 0.14,
      shakeRandomImpulse: 0.06,
      spawnBaseY: 0.58,
      spawnRangeY: 0.08,
      spawnRadius: 0.68,
      spawnJitter: 0.06,
      colliderBottomHalfHeight: 0.09,
      colliderBottomY: 0.11,
      colliderBottomRadius: 1.5,
      colliderWallHalfWidth: 0.41,
      colliderWallHalfDepth: 0.12,
      colliderWallHalfHeight: 0.9,
      colliderWallY: 1,
      colliderWallRadius: 1.63,
      containmentRadius: 1.5,
      spillDirectionX: -1,
      spillForceMultiplier: 1,
      spillMinimumSpeed: 2,
      spillRandomSpeed: 0.8,
      spillLiftSpeed: 0.55,
      spillFanSpeed: 0.22,
      spillRandomZ: 0.25,
      spillTorque: 0.9,
      spillSideImpulse: 1.15,
      spillSideImpulseVariance: 0.12,
      visual: {
        outerBottomY: 0.03,
        outerBottomRadius: 1.56,
        innerBottomY: 0.2,
        innerBottomRadius: 1.44,
        innerRimRadius: 1.63,
        outerRimRadius: 1.87,
        rimRadius: 1.75,
        rimTube: 0.12,
        rimY: 1.9,
        segments: 48,
      },
    },
    alignment: {
      durationMs: 900,
      lineUpEnd: 0.68,
      lift: 0.52,
    },
    settlement: { stableFrames: 14 },
    safety: { margin: 0.16, bounce: 0.52 },
  },
} as const

export type PhysicsDiceConfig = typeof PHYSICS_DICE_CONFIG
